name:
  pypsa-dashboard

channels:
  - conda-forge

dependencies:
  - python
  - pip
  - ipython
  - pre-commit
  - mamba
  - yaml
  - pypsa
  - cartopy
  - networkx
  - hvplot
  - geoviews
  - nodejs
  - bokeh
  - holoviews
  - xarray
  - pandas
  - geopandas
  - numpy
  - panel
  - jupyterlab
  - atlite
